### ISSUE TITLE
Is this still running?

### ISSUE THREAD

**Issue by chozzz** [thisgamesux/linux-csgo-external#19]
I tried to run it and failed to get it working..

Here's my log

```
> sudo ./csgo_external 
s0beit linux hack version 1.3
Log Path [/home/user/dev/gits/linux-csgo-external/]
```

I am using Ubuntu 14.04

> Linux user-S551LB 4.4.0-36-generic #55~14.04.1-Ubuntu SMP Fri Aug 12 11:49:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yukoulah** [comment]
F7, F8, F9 do nothing in console?
have you a bind key for +alt1?

**Comment by yukoulah** [comment]
sorry use https://github.com/McSwaggens/linux-csgo-external maybe

**Comment by chozzz** [comment]
@yukoulah I haven't bound any key to `+alt1`, but McSwaggens got mine working. Thanks for your help.
