### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Watterx** [thisgamesux/linux-csgo-external#2]
Hi, im very new to Linux overall, so I'm very sorry if this is a roocky stupid mistake, but I can't make this to work ! Hopefully you can help me out.

root@abeneth:/home/abeneth/Hackers/Linuxhacker# g++ -Wall -W -Werror main.cpp -o linuxhack
In file included from /usr/include/c++/4.8/unordered_map:35:0,
                 from remote.hpp:13,
                 from main.cpp:3:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
main.cpp: In function ‘int main()’:
main.cpp:55:13: error: ‘auto’ changes meaning in C++11; please remove it [-Werror=c++0x-compat]
         for(auto region : csgo.regions) {
             ^
main.cpp:55:18: error: ‘region’ does not name a type
         for(auto region : csgo.regions) {
                  ^
main.cpp:63:9: error: expected ‘;’ before ‘usleep’
         usleep(500);
         ^
main.cpp:64:5: error: expected primary-expression before ‘}’ token
     }
     ^
main.cpp:64:5: error: expected ‘)’ before ‘}’ token
main.cpp:64:5: error: expected primary-expression before ‘}’ token
main.cpp:64:5: error: expected ‘;’ before ‘}’ token
cc1plus: all warnings being treated as errors

**Comment by thereals0beit** [comment]
You're indeed compiling it incorrectly, you're using g++ and only compiling the main.cpp file, and on top of that you aren't using c++11 switches.

I installing cmake, and running the make file.

**Comment by Watterx** [comment]
wow thanks for the quick response ill try it out and edit the comment after :)

**Comment by Watterx** [comment]
Ill bump in case you don't get the message when I edit sorry!

**Comment by Watterx** [comment]
abeneth@abeneth:~/Hackers$ cmake '/home/abeneth/Hackers/CMakeLists.txt' 
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/abeneth/Hackers
abeneth@abeneth:~/Hackers$ make
Scanning dependencies of target csgo_external
[ 20%] Building CXX object CMakeFiles/csgo_external.dir/log.cpp.o
In file included from /home/abeneth/Hackers/log.hpp:3:0,
                 from /home/abeneth/Hackers/log.cpp:1:
/usr/include/c++/4.8/string:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
make[2]: **\* [CMakeFiles/csgo_external.dir/log.cpp.o] Error 1
make[1]: **\* [CMakeFiles/csgo_external.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Watterx** [comment]
All right, I had to install "sudo apt-get install gcc-multilib g++-multilib" leaving this in case theres another noob out there like me lol.

Thanks :)
