### ISSUE TITLE
Turning the hack on/off

### ISSUE THREAD

**Issue by L1nkus** [thisgamesux/linux-csgo-external#6]
Hello, I so far enjoyed the hack, but I would like to ask, is there a way to change something in the code, to gain the possibility of switching the hack on/off using a key? I'm new to linux programming and I would like to know if it's possible to do and how.

**Comment by rajiohead** [comment]
look at  the lines
```
 while(csgo.IsRunning()) {
        hack::Glow(&csgo, &client, addressOfGlowPointer);

        usleep(5000);
    }
```
you could:
- wait for a keypress
- wait for a signal
- wait for a command
if that's too hard, just make a simple script that closes the program with a key, and opens it with another

**Comment by ghost** [comment]
You could bind a command to 2 different keys on runs the command and one kills it.
the 2 commands would be
`./csgo_external` and to kill it would be `pkill csgo_external`

**Comment by bryantwilliam** [comment]
Would we need to bind these keys on our distro settings or is there a way to do this in-game? If only the former is possible, is there a way to make it so those binds only work in csgo so that it doesn't randomly do it if I'm doing something else?

**Comment by Superchet** [comment]
I think it would be smart to disable and enable the bind just before you start csgo.

**Comment by bryantwilliam** [comment]
That'd be annoying >:( But I guess it isn't any better than starting ./csgo_external before you start csgo anyway.

**Comment by Superchet** [comment]
I don´t see a different solution, do you?

**Comment by bryantwilliam** [comment]
Nope, that's why I asked :P

**Comment by ghost** [comment]
what i said you do is through distro settings and it wouldnt do anything that harms your pc when the game is off. pkill only kills csgo external and the other starts it but a terminal wont really do much.

**Comment by bryantwilliam** [comment]
I thought there may be a way to only make the shortcuts listen to key presses if the game is open (possibly through client or hack), but that's prob too hard. But don't worry, I did it through distro setting anyway.

**Comment by ghost** [comment]
there is. but i am to lazy to code it or figure it out.

**Comment by bryantwilliam** [comment]
No worries I would myself but I guess it just comes down to ignorance in C++ lol.

**Comment by Superchet** [comment]
Gogobebe2, why don´t you just learn it? xD

**Comment by Superchet** [comment]
http://www.learncpp.com/

**Comment by maaatts** [comment]
Because learning things takes time and he wants somebody else to do it for him. ;)

**Comment by Superchet** [comment]
I´m not that well myself, but the fun thing about it is learning :).
Outside of school I try and learn new things about code, it´s fun and gets you one step closer.

**Comment by gogobebe2** [comment]
I'm a Java/Python/Haskell Programmer and I am learning other things. Currently I am too busy, no need to try and boost your ego by trying to explain to me the unprovable, implied claim that I'm an idiot for not learning it. I am currently earning $300/week (NZD) from my small software "business" (I dont pay tax lol). I'm 15 years old and I have a lot of school work as well. I learn things, just not EVERYTHING.

**Comment by Superchet** [comment]
Easy there, I didn't save that.

**Comment by gogobebe2** [comment]
I hate people who assume someone and judge them right off the bat. Forgive me for being so hostile, but you needed to hear this. No, you didn't say that. But you were clearly implying it.

**Comment by Superchet** [comment]
Pretty sure maaatts was, not me

**Comment by gogobebe2** [comment]
You sent me a link to that website. You assumed I was too ignorant to google "c++ tutorial". Stop being so pretentious.

**Comment by Superchet** [comment]
It's not like I was serious and was trying to act all "cool".

**Comment by Superchet** [comment]
It was like a joke, as a reply to "No worries I would myself but I guess it just comes down to ignorance in C++ lol"

**Comment by ghost** [comment]
if you know a resource share it. don't get angry if you can learn from it.

**Comment by bryantwilliam** [comment]
I never asked for it and I don't currently want or need it. It was clearly passive aggression. I don't think github is the place for this type of discussion anyway.

**Comment by Superchet** [comment]
Look, I'm sorry, I didn't want it to come off this way :/

**Comment by Superchet** [comment]
Over?

**Comment by bryantwilliam** [comment]
yep

**Comment by ghost** [comment]
gogobebe2 i have to say that i would not be proud of making money off of code...

**Comment by Superchet** [comment]
Why? I mean I wouldn't either, but do you have a valid reason?

**Comment by bryantwilliam** [comment]
I wouldn't be proud if I was bill gates either. LOL, BULLSHIT.

**Comment by ghost** [comment]
I make code everyday but I don't make people pay for it. A real programmer doesn't brag about who is better but works with others to make their best work. a real programmer does it for passion not for money.

**Comment by Superchet** [comment]
I totally agree, but look at pianists. Sad to see them play an instrument that well and only share it for money.

**Comment by gogobebe2** [comment]
I felt threatened, therefore I did so to explain I am not an ignorant helloworlder. I do it for passion, money is just that cool extra - especially when I'm 15 and I literally don't need money at all (except for going out and stuff where I'd spend less than $100 now and then).

**Comment by ghost** [comment]
if you have to make a living it is fine. I could make $50 000 a month, do i? no i don't  need the money like pianists do.

**Comment by ghost** [comment]
but i an 14. I don't take money i take experience.

**Comment by Superchet** [comment]
I guess that's all figured out :)
Went from toggling wh in CS:GO in linux to... This

**Comment by bryantwilliam** [comment]
I take both :P And you're extremely arrogant if you think you're 14 years old and can make 50k a month. LOL, get outta here mate.

**Comment by bryantwilliam** [comment]
Unsubscribing from this issue thread, feel free to email me.

**Comment by Superchet** [comment]
Just close it, cya in other ones guys :)

**Comment by ghost** [comment]
You obviously have never been in the web design and hosting business. Any ways I am taking my aim bot and going to help someone else.

**Comment by Superchet** [comment]
Oh, okay, bye :/

**Comment by ghost** [comment]
Adios
